version: "3.8"

services:
  db:
    # Use regular postgres by default
    image: postgres
    # Use postgis for spatial apps
    #image: postgis/postgis
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: ./django
    command: gunicorn myproject.wsgi -b 0.0.0.0:8000
    env_file: .env
    volumes:
      - static_files:/static
      - media:/media
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./nginx
    ports:
      - "$APP_PORT:80"
    depends_on:
      - app
    volumes:
      - static_files:/static
      - media:/media

volumes:
  db_data:
  static_files:
  media:
