version: "3.8"

services:
  db:
    # Use regular postgres by default
    image: postgres
    # Use postgis for spatial apps
    #image: postgis/postgis
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "$APP_PORT:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: {}
